# Generated by Django 4.2 on 2023-07-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compsite_pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='doc/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compsite_pro.topic')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
