# Generated by Django 4.2 on 2023-07-12 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compsite_pro', '0002_subjectentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectentry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='compsite_pro.topic'),
        ),
    ]
