# Generated by Django 4.2 on 2023-07-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compsite_pro', '0004_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
